# Generated by Django 5.1 on 2024-09-03 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('total_fame', models.CharField(max_length=50)),
                ('kill_fame', models.CharField(max_length=50)),
                ('playerkill', models.IntegerField(max_length=40)),
                ('guild_member', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5)),
                ('server_name', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('N.America', 'N.America')], default='Asia', max_length=12)),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=19)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
