# Generated by Django 5.1 on 2024-09-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_custom_user_groups_custom_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='playerkill',
            field=models.IntegerField(default=0),
        ),
    ]
